---
name: lambda
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: 'a shortcut for sub {...}'
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=lambda
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/lambda/trunk
requires:
  perl: 5.6.2
build_requires:
  Module::Build: 0.28
  Test::More: 0
provides:
  lambda:
    file: lib/lambda.pm
    version: v0.0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
